# Generated by Django 3.1.4 on 2020-12-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20201219_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('average_battery_voltage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('max_battery_voltage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('min_battery_voltage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('battery_critical_state_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('one_hour_samples_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('lock_mode_entry_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('factory_mode_entry_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('gsm_sync_button_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('stove_on_off_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('daily_power_consumption', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('left_stove_cooktime', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('right_stove_cooktime', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('others', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
