# Generated by Django 3.1.4 on 2021-01-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dailyusagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusagedata',
            name='average_cooking_time_per_use',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyusagedata',
            name='average_power_consumption_per_use',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyusagedata',
            name='daily_cooking_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyusagedata',
            name='when_date',
            field=models.DateField(null=True),
        ),
    ]
