# Generated by Django 3.1.4 on 2021-02-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20210218_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitnumber',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitnumber',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
