# Generated by Django 3.1.4 on 2021-03-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210218_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitnumber',
            name='unit_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
